### ISSUE TITLE
csv export broken on "Ed,Edd n Eddy: The Mis-Edventures"

### ISSUE THREAD

**Issue by PatrickvL** [JayFoxRox/xbox-game-databases#3]
Since the csv separator character (a comma) is contained in the "Ed,Edd n Eddy: The Mis-Edventures" title, splitting this row results in all cells being incorrectly shifted one column aside.

**Comment by PatrickvL** [comment]
Edit : This happens in xqemu-compatibility-inspector.py, haven't checked the rest of this repo

**Comment by JayFoxRox** [comment]
This seems to work fine for me?

`./xqemu-compatibility-inspector.py  | grep Ed` gives

```
['Driv3r', 'Driver: Parallel Lines', 'Ed, Edd n Eddy: The Mis-Edventures', 'Ford Mustang: The Legend Lives', 'Ford Vs. Chevy', 'Gladiator: Sword of Vengeance', 'Hummer: Badlands', 'JSRF: Jet Set Radio Future', 'Just Cause', 'Maximum Chase', 'Melbourne Cup Challenge', 'Midnight Club II']
Needs retest: ['Driv3r', 'Driver: Parallel Lines', 'Ed, Edd n Eddy: The Mis-Edventures', 'Ford Mustang: The Legend Lives', 'Ford Vs. Chevy', 'Gladiator: Sword of Vengeance', 'Hummer: Badlands', 'JSRF: Jet Set Radio Future', 'Just Cause', 'Maximum Chase', 'Melbourne Cup Challenge', 'Midnight Club II']
```
The name is correct, so I'm sure the rest is also correct.

Which locale, charset and python distribution are you using?
This script is intended for en_US (C should also work?), UTF-8, Python 3.

Also how does this problem manifest? Do you get an error or something?

**Comment by PatrickvL** [comment]
It seems python does a better job at splitting up separators than Excel, as I was basing my report on the behaviour of that (little known Microsoft) tool ;)

**Comment by JayFoxRox** [comment]
[If you just want to look at the sheet, you can also use the google sheets frontend](https://docs.google.com/spreadsheets/d/1sVtQ9SNPathKAMCqfYtvJQP0bs0UeLzP9otPHvZDMwE/edit#gid=709879345).

The whole idea of this script is to aggregate information and also show affected code by pulling data from GitHub. So using Excel or the Google frontend isn't beneficial at all.

CSV is also very loosely defined, so unless you test this particular CSV variant + CSV parser implementation (the one that comes with Python 3) any bug report would be invalid anyway.

For your information, the output of this script looks like this:

![Screenshot of xqemu-compatibility-inspector](https://user-images.githubusercontent.com/360330/51677692-b2867a80-1fda-11e9-9af0-aadfa19c93ab.png)

It's output is critical for identifying the same code across different versions and finding games with the same or similar issues. It has been used to fix hundreds of problems with games. My personal focus in XQEMU was typically put on those problems which affect 20 or more games.
The other tools in this repository can also assist, by identifying games with the same engine.

Being open-source, it's very easy to construct variation of these tools for various other purposes.
